apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: cloud-app
type: Opaque
stringData:
  CONNECTION_STRING: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=cloudappstorage2026;AccountKey=4nLcjpC+uB8vAyYMoURdEzm+SsTn9irMR4iDoAS1gyRJsgirpMo1R8aC2bYN/TttqZK0euSkh2RC+AStxtNPIw==;BlobEndpoint=https://cloudappstorage2026.blob.core.windows.net/;FileEndpoint=https://cloudappstorage2026.file.core.windows.net/;QueueEndpoint=https://cloudappstorage2026.queue.core.windows.net/;TableEndpoint=https://cloudappstorage2026.table.core.windows.net/"