apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: cloud-app
type: Opaque
stringData:
  CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=<STORAGE_ACCOUNT>;AccountKey=<KEY>;EndpointSuffix=core.windows.net"